sylius_resource:
    settings:
        paginate: false
    resources:
        app.ville:
            driver: doctrine/orm
            classes:
                model: AppBundle\Entity\Ville

        app.quartier:
            driver: doctrine/orm
            classes:
                model: AppBundle\Entity\Quartier

        app.user:
            driver: doctrine/orm
            classes:
                model: AppBundle\Entity\User

        app.categorie:
            driver: doctrine/orm
            classes:
                model: AppBundle\Entity\Categorie
