sylius_resource:
    settings:
        paginate: false
    resources:
        app.ville:
            driver: doctrine/orm
            classes:
                model: AppBundle\Entity\Ville

        app.quartier:
            driver: doctrine/orm
            classes:
                model: AppBundle\Entity\Quartier

        app.user:
            driver: doctrine/orm
            classes:
                model: AppBundle\Entity\User

        app.categorie:
            driver: doctrine/orm
            classes:
                model: AppBundle\Entity\Categorie

        app.boitier:
            driver: doctrine/orm
            classes:
                model: AppBundle\Entity\Boitier

        app.carburant:
            driver: doctrine/orm
            classes:
                model: AppBundle\Entity\Carburant

        app.marque:
            driver: doctrine/orm
            classes:
                model: AppBundle\Entity\Marque
