imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:           stream
            path:           'php://stderr'
            level:          info
        main_critical:
            type:           fingers_crossed
            action_level:   critical
            handler:        grouped_critical
        grouped_critical:
            type:           group
            members:        [streamed_critical, buffered_critical]
        streamed_critical:
            type:           stream
            path:           'php://stderr'
            level:          info
        buffered_critical:
            type:           buffer
            handler:        swift_critical
        swift_critical:
            type:           swift_mailer
            from_email:     "%maileruser%"
            to_email:       "%maileruser%"
            subject:        Une erreur critique est survenue !
            level:          info

vich_uploader:
    db_driver: orm
    storage:   gaufrette

    mappings:
        voiture_image:
            # uri_prefix: /client/app/images/voitures
            uri_prefix: '%awss3baseurl%'
            # upload_destination: %kernel.root_dir%/../web/client/app/images/voitures
            upload_destination: nicetruc_storage_s3
            namer: nicetruc.namer.voiture

            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true

aws:
    version: latest
    region: '%awss3region%'
    credentials:
        key: '%awss3key%'
        secret: '%awss3secretkey%'
    S3:
        version: '2006-03-01'