imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: critical
            handler:      grouped
        grouped:
            type:    group
            members: [streamed, buffered]
        streamed:
            type:  stream
            path:  'php://stderr'
#            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        buffered:
            type:    buffer
            handler: swift
        console:
            type:  console
        swift:
            type:       swift_mailer
            from_email: "%maileruser%"
            to_email:   "%maileruser%"
            subject:    Error critique nicetruc! 
            level:      debug

vich_uploader:
    db_driver: orm
    storage:   gaufrette

    mappings:
        voiture_image:
            # uri_prefix: /client/app/images/voitures
            uri_prefix: '%awss3baseurl%'
            # upload_destination: %kernel.root_dir%/../web/client/app/images/voitures
            upload_destination: nicetruc_storage_s3
            namer: nicetruc.namer.voiture

            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true

aws:
    version: latest
    region: '%awss3region%'
    credentials:
        key: '%awss3key%'
        secret: '%awss3secretkey%'
    S3:
        version: '2006-03-01'