fos_elastica:
    clients:
        default: { host: '%elastichost%', port: '%elasticport%' }
    indexes:
        nicetruc:
            settings:
                index:
                    analysis:
                        tokenizer:
                            nGram:
                                type:     nGram
                                min_gram: 3
                                max_gram: 3
                        analyzer:
                            custom_analyzer :
                                type     :    custom
                                tokenizer:    nGram
                                filter   :    [stop, asciifolding ,lowercase, snowball, elision, worddelimiter]
                            custom_search_analyzer :
                                type     :    custom
                                tokenizer:    standard
                                filter   :    [stop, asciifolding ,lowercase, snowball, elision, worddelimiter]
                        filter:
                            snowball:
                                type:     snowball
                            elision:
                                type:     elision
                                articles: [l, m, t, qu, n, s, j, d]
                            stopwords:
                                type:      stop
                                ignore_case : true
                            worddelimiter :
                                type:      word_delimiter
            types:
                voiture:
                    mappings:
                        id: ~
                        prix: 
                            type: integer
                        kmParcouru: 
                            type: integer
                        boitier.id: ~
                        boitier.libelleBoitier: { analyzer: custom_analyzer }
                        carburant.id: ~
                        carburant.libelleCarburant: { analyzer: custom_analyzer }
                        modeleMarque.marque.id: ~
                        modeleMarque.marque.libelleMarque: { analyzer: custom_analyzer }
                        modeleMarque.modele.id: ~
                        modeleMarque.modele.libelleModele: { analyzer: custom_analyzer }
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Voiture
                        finder: ~
                        provider: ~
                        listener: ~     
                        repository: AppBundle\ElasticaBundle\SearchRepository\VoitureRepository
