fos_elastica:
    clients:
        default: { host: '%elastichost%', port: '%elasticport%' }
    indexes:
        nicetruc:
            index_name: app_%kernel.environment%
            settings:
                index:
                    analysis:
                        analyzer:
                            custom_analyzer :
                                type     :    custom
                                tokenizer:    nGram
                                filter   :    [stopwords, asciifolding ,lowercase, snowball, elision, worddelimiter]
                            custom_search_analyzer :
                                type     :    custom
                                tokenizer:    standard
                                filter   :    [stopwords, asciifolding ,lowercase, snowball, elision, worddelimiter]
                        tokenizer:
                            nGram:
                                type:     nGram
                                min_gram: 2
                                max_gram: 20
                        filter:
                            snowball:
                                type:     snowball
                                language: French
                            elision:
                                type:     elision
                                articles: [l, m, t, qu, n, s, j, d]
                            stopwords:
                                type:      stop
                                stopwords: [_french_]
                                ignore_case : true
                            worddelimiter :
                                type:      word_delimiter
            types:
                voiture:
                    mappings:
                        id:
                            type: integer
                        prix:
                            type: integer
                        kmParcouru:
                            type: integer
                        boitier:
                            type: "object"
                            properties:
                                id: ~
                                libelleBoitier:
                                    index_analyser: custom_analyzer
                                    search_analyzer: custom_search_analyzer
                        carburant:
                            type: "object"
                            properties:
                                id: ~
                                libelleCarburant:
                                    index_analyser: custom_analyzer
                                    search_analyzer: custom_search_analyzer
                        modeleMarque:
                            type: "object"
                            properties:
                                id: ~
                                marque:
                                    type: "object"
                                    properties:
                                        id: ~
                                        libelleMarque:
                                            index_analyser: custom_analyzer
                                            search_analyzer: custom_search_analyzer
                                modele:
                                    type: "object"
                                    properties:
                                        id: ~
                                        libelleModele:
                                            index_analyser: custom_analyzer
                                            search_analyzer: custom_search_analyzer
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Voiture
                        finder: ~
                        provider: ~
                        listener: ~     
