app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

app_ville:
#    defaults:
#        _sylius:
#            flash: ~
    resource: app.ville
    type: sylius.api
    prefix: /api

app_quartier:
    resource: app.quartier
    type: sylius.api
    prefix: /api

#app_user:
#    resource: app.user
#    type: sylius.api
#    prefix: /api

app_categorie:
    resource: app.categorie
    type: sylius.api
    prefix: /api

app_categorie_by_libelle:
    path: /categories/{libelleCategorie}
    methods: [GET]
    defaults:
        _controller: app.controller.categorie:showAction
        _sylius:
            criteria:
                libelleCategorie: $libelleCategorie
    prefix: /api

app_boitier:
    resource: app.boitier
    type: sylius.api
    prefix: /api

app_carburant:
    resource: app.carburant
    type: sylius.api
    prefix: /api

app_marque:
    resource: app.marque
    type: sylius.api
    prefix: /api

app_modele:
    resource: app.modele
    type: sylius.api
    prefix: /api

app_modelemarque:
    resource: app.modelemarque
    type: sylius.api
    prefix: /api

app_modelesmarques:
    path: /marques/{idMarque}/modeles/{idModele}
    methods: [GET]
    defaults:
        _controller: app.controller.modeleMarque:showAction
        _sylius:
            criteria:
                marque: [idMarque]
                modele: [idModele]

app_voiture:
    resource: app.voiture
    type: sylius.api
    prefix: /api

