app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app_ville:
#    defaults:
#        _sylius:
#            flash: ~
    resource: app.ville
    type: sylius.api
    prefix: /api

app_quartier:
    resource: app.quartier
    type: sylius.api
    prefix: /api

app_user:
    resource: app.user
    type: sylius.api
    prefix: /api

app_categorie:
    resource: app.categorie
    type: sylius.api
    prefix: /api

app_boitier:
    resource: app.boitier
    type: sylius.api
    prefix: /api

app_carburant:
    resource: app.carburant
    type: sylius.api
    prefix: /api

app_marque:
    resource: app.marque
    type: sylius.api
    prefix: /api