# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    nicetruc.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: nicetruc_user_registration }

    nicetruc.login.success.handler:
        class: AppBundle\Handler\LoginSuccessHandler
        arguments: [@security.token_storage,@security.authorization_checker,@router]

    nicetruc.login.failure.handler:
        class: AppBundle\Handler\LoginFailureHandler
        arguments: [@router]
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
