# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    nicetruc.user.class:
        class: AppBundle\Entity\User

    nicetruc.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: nicetruc_user_registration }

    nicetruc.form.profile:
        class: AppBundle\Form\ProfileFormType
        arguments: ["AppBundle\Entity\User"]
        tags:
            - { name: form.type, alias: nicetruc_user_profile }

    nicetruc.form.change.password:
        class: AppBundle\Form\ChangePasswordFormType
        arguments: ["AppBundle\Entity\User"]
        tags:
            - { name: form.type, alias: nicetruc_user_change_password }

    nicetruc.form.ville:
        class: AppBundle\Form\VilleType
        tags:
            - { name: form.type, alias: nicetruc_ville }

    nicetruc.form.ville:
        class: AppBundle\Form\VilleType
        tags:
            - { name: form.type, alias: nicetruc_ville }

    nicetruc.login.success.handler:
        class: AppBundle\Handler\LoginSuccessHandler
        arguments: [@security.token_storage,@security.authorization_checker,@router]

    nicetruc.login.failure.handler:
        class: AppBundle\Handler\LoginFailureHandler
        arguments: [@router]
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
