<?php

namespace AppBundle\Entity;

//use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;
use Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository;

/**
 * MarqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarqueRepository extends EntityRepository
{
    public function findMarqueWithModele(){
        $resultatMarques = $this->createQueryBuilder('a')
            ->join('a.modeleMarques','b')
            ->addSelect('b')
            ->join('b.modele','c')
            ->addSelect('c')
            ->getQuery()
            ->getArrayResult();
        foreach($resultatMarques as $key=> $marque){
            $modeles=array();
            foreach($marque['modeleMarques'] as $modeleMarque){
                $modele=$modeleMarque['modele'];
                $modele['modeleMarque']=$modeleMarque['id'];;
                $modeles[]=$modele;
                // $modeles[]=$modeleMarque['modele'];
            }
            $resultatMarques[$key]['modeles']=$modeles;
        }
        return $resultatMarques;

    }

    public function findMarques(){
        $qb = $this->createQueryBuilder('m');

        return $this->getPaginator($qb);
    }


}


