<?php

namespace AppBundle\Entity;

/**
 * PostulantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostulantRepository extends \Doctrine\ORM\EntityRepository
{
	public function customFindByVoiture($idVoiture){
        $resultat = $this->createQueryBuilder('p')
        		->join('p.voiture','voiture')
                ->where('voiture.isPublish=:isPublish')
                ->setParameter('isPublish',true)
                ->getQuery()
                ->getResult();
                return $resultat;
    }

}
